### PR TITLE
Adding eunit setup capability

### PR DESCRIPTION
**Pull request by kektobiologist**

### CODE REVIEW

**Comment by srijan** [comment]
We can submit this upstream for better feedback.
https://github.com/ninenines/erlang.mk

**Comment by kektobiologist** [comment]
Done https://github.com/ninenines/erlang.mk/pull/824

**Comment by kektobiologist** [comment]
Essen says he doesn't have time for a couple more weeks to review this. Should we apply the PR on this repo and then sync with upstream later on?

**Comment by kektobiologist** [comment]
I've made changes in ninenines#824 as he suggested so mostly it will be accepted as is

**Comment by srijan** [comment]
Please do `make clean` before committing. `erlang.mk` file should not be committed here.

**Comment by kektobiologist** [comment]
Done

**Pull request merged**
