### PR TITLE
Support rock in parallel for elvis

### PR DESCRIPTION
**Pull request by bilalhusain**
A recent [pull request](https://github.com/inaka/elvis_core/pull/107) has added parallel processing of files to [elvis_core](https://github.com/inaka/elvis_core). The proposed change enables `erlang.mk` to use this enhancement.

### CODE REVIEW

**Comment by srijan** [comment]
In the [corresponding pull request in elvis](https://github.com/inaka/elvis/pull/499), the author has given an "auto" option for parallelism which uses `erlang:system_info(schedulers)` to auto calculate the number of parallel processes.

Can we use something similar here? If `ELVIS_PARALLEL_JOBS` is set as auto (and default should be auto), then it should auto-calculate using available schedulers.

**Comment by srijan** [comment]
Also, it could be a good idea to submit this PR to this's repo's upstream repo: https://github.com/ninenines/erlang.mk

**Comment by bilalhusain** [comment]
The "auto" option is supported in command line arguments.

Handling similar behaviour for Makefile variable was getting slightly messy. Proposing setting the variable directly as `erlang:system_info(schedulers)`. Commit added.

**Comment by bilalhusain** [comment]
> Also, it could be a good idea to submit this PR to this's repo's upstream repo: https://github.com/ninenines/erlang.mk

At present, they treat Elvis as an external plugin. The [external plugin](https://github.com/inaka/elvis.mk/blob/master/plugins.mk) supports command line only and uses an outdated version.

**Pull request closed without merging**
